services:
  tilde-server:
    build: 
      context: .
      dockerfile: Containerfile
      args:
          JOIN_PASSWORD: "#CHANGE_ME#"
          SERVER_DOMAIN: "#CHANGE_ME#"
          ADMIN_EMAIL: "#CHANGE_ME#"
          ROOT_PASSWORD: "#CHANGE_ME#"
          container: "podman"
    container_name: tilde-server
    volumes:
      - user-data:/home
      - app-data:/opt/cornell-tilde/var
      - system-state:/etc
    ports:
      - "2222:22"
      - "8080:80"
    environment:
      - container="podman"

volumes:
  user-data:
  app-data:
  system-state: