name: Validate Deployment Scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache Container Layers
        uses: actions/cache@v5
        with:
          path: ~/.local/share/containers/storage
          key: ${{ runner.os }}-podman-${{ hashFiles('**/Containerfile') }}
          restore-keys: |
            ${{ runner.os }}-podman-${{ hashFiles('**/Containerfile') }}
            ${{ runner.os }}-podman-

      - name: Build the Container image
        run: |
          podman build . \
            --tag tilde-cornell-dev \
            --build-arg JOIN_PASSWORD="${{ vars.JOIN_PASSWORD }}" \
            --build-arg SERVER_DOMAIN="${{ vars.SERVER_DOMAIN }}" \
            --build-arg ADMIN_EMAIL="${{ vars.ADMIN_EMAIL }}" \
            --build-arg container="podman"\
            --build-arg ROOT_PASSWORD="${{ vars.ROOT_PASSWORD }}"
