name: Validate Deployment Scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Cache Podman Image
        id: cache-podman-image
        uses: actions/cache@v5
        with:
          path: /tmp/podman-cache
          key: ${{ runner.os }}-podman-${{ hashFiles('**/Containerfile') }}
          restore-keys: |+
            ${{ runner.os }}-podman-${{ hashFiles('**/Containerfile') }}
            ${{ runner.os }}-podman-
              
      - name: Load Cached Image
        if: steps.cache-podman-image.outputs.cache-hit == 'true'
        run: |
          podman load -i /tmp/podman-cache/tilde-cornell-dev.tar

      - name: Build the Podman image
        id: build-podman-image
        run: |
          podman build . \
            --tag tilde-cornell-dev \
            --build-arg JOIN_PASSWORD="${{ vars.JOIN_PASSWORD }}" \
            --build-arg SERVER_DOMAIN="${{ vars.SERVER_DOMAIN }}" \
            --build-arg ADMIN_EMAIL="${{ vars.ADMIN_EMAIL }}" \
            --build-arg container="podman"\
            --build-arg ROOT_PASSWORD="${{ vars.ROOT_PASSWORD }}"

      - name: Save Image to Cache
        if: steps.build-podman-image.outcome == 'success'
        run: |
          mkdir -p /tmp/podman-cache
          podman save --format oci-archive -o /tmp/podman-cache/tilde-cornell-dev.tar tilde-cornell-dev
